"""create spdk tables

Revision ID: cd40e3f3d8d6
Revises: 5ea9f662ced4
Create Date: 2025-09-24 11:29:25.218071+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd40e3f3d8d6'
down_revision = '5ea9f662ced4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_spdk_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_global_basenqn', sa.String(length=255), nullable=False),
    sa.Column('spdk_global_worker_cores', sa.String(length=255), nullable=False),
    sa.Column('spdk_global_kernel', sa.Boolean(), nullable=False),
    sa.Column('spdk_global_ana', sa.Boolean(), nullable=False),
    sa.Column('spdk_global_rdma', sa.Boolean(), nullable=False),
    sa.Column('spdk_global_xport_referral', sa.Boolean(), nullable=False),
    sa.Column('spdk_global_max_queue_depth', sa.Integer(), nullable=False),
    sa.Column('spdk_global_max_io_qpairs', sa.Integer(), nullable=False),
    sa.Column('spdk_global_in_caps', sa.Integer(), nullable=False),
    sa.Column('spdk_global_num_shared_buffers', sa.Integer(), nullable=False),
    sa.Column('spdk_global_huge_page_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_global')),
    sqlite_autoincrement=True
    )
    op.create_table('services_spdk_host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_host_hostnqn', sa.String(length=255), nullable=False),
    sa.Column('spdk_host_dhchap_key', sa.Text(), nullable=True),
    sa.Column('spdk_host_dhchap_ctrl_key', sa.Text(), nullable=True),
    sa.Column('spdk_host_dhchap_dhgroup', sa.Integer(), nullable=False),
    sa.Column('spdk_host_dhchap_hash', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_host')),
    sa.UniqueConstraint('spdk_host_hostnqn', name=op.f('uq_services_spdk_host_spdk_host_hostnqn')),
    sqlite_autoincrement=True
    )
    op.create_table('services_spdk_port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_port_index', sa.Integer(), nullable=False),
    sa.Column('spdk_port_addr_trtype', sa.Integer(), nullable=False),
    sa.Column('spdk_port_addr_trsvcid', sa.String(length=255), nullable=True),
    sa.Column('spdk_port_addr_traddr', sa.String(length=255), nullable=False),
    sa.Column('spdk_port_addr_adrfam', sa.Integer(), nullable=False),
    sa.Column('spdk_port_inline_data_size', sa.Integer(), nullable=True),
    sa.Column('spdk_port_max_queue_size', sa.Integer(), nullable=True),
    sa.Column('spdk_port_pi_enable', sa.Boolean(), nullable=True),
    sa.Column('spdk_port_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_port')),
    sa.UniqueConstraint('spdk_port_index', name=op.f('uq_services_spdk_port_spdk_port_index')),
    sqlite_autoincrement=True
    )
    op.create_table('services_spdk_subsys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_subsys_name', sa.String(), nullable=False),
    sa.Column('spdk_subsys_subnqn', sa.String(length=223), nullable=False),
    sa.Column('spdk_subsys_serial', sa.String(), nullable=False),
    sa.Column('spdk_subsys_allow_any_host', sa.Boolean(), nullable=False),
    sa.Column('spdk_subsys_pi_enable', sa.Boolean(), nullable=True),
    sa.Column('spdk_subsys_qid_max', sa.Integer(), nullable=True),
    sa.Column('spdk_subsys_ieee_oui', sa.Integer(), nullable=True),
    sa.Column('spdk_subsys_ana', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_subsys')),
    sa.UniqueConstraint('spdk_subsys_name', name=op.f('uq_services_spdk_subsys_spdk_subsys_name')),
    sa.UniqueConstraint('spdk_subsys_serial', name=op.f('uq_services_spdk_subsys_spdk_subsys_serial')),
    sa.UniqueConstraint('spdk_subsys_subnqn', name=op.f('uq_services_spdk_subsys_spdk_subsys_subnqn')),
    sqlite_autoincrement=True
    )
    op.create_table('services_spdk_host_subsys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_host_subsys_host_id', sa.Integer(), nullable=False),
    sa.Column('spdk_host_subsys_subsys_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spdk_host_subsys_host_id'], ['services_spdk_host.id'], name=op.f('fk_services_spdk_host_subsys_spdk_host_subsys_host_id_services_spdk_host')),
    sa.ForeignKeyConstraint(['spdk_host_subsys_subsys_id'], ['services_spdk_subsys.id'], name=op.f('fk_services_spdk_host_subsys_spdk_host_subsys_subsys_id_services_spdk_subsys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_host_subsys')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('services_spdk_host_subsys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_spdk_host_subsys_spdk_host_subsys_host_id'), ['spdk_host_subsys_host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_spdk_host_subsys_spdk_host_subsys_subsys_id'), ['spdk_host_subsys_subsys_id'], unique=False)

    op.create_table('services_spdk_namespace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_namespace_nsid', sa.Integer(), nullable=False),
    sa.Column('spdk_namespace_subsys_id', sa.Integer(), nullable=False),
    sa.Column('spdk_namespace_device_type', sa.Integer(), nullable=False),
    sa.Column('spdk_namespace_device_path', sa.String(length=255), nullable=False),
    sa.Column('spdk_namespace_filesize', sa.Integer(), nullable=True),
    sa.Column('spdk_namespace_device_uuid', sa.String(length=40), nullable=False),
    sa.Column('spdk_namespace_device_nguid', sa.String(length=40), nullable=False),
    sa.Column('spdk_namespace_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['spdk_namespace_subsys_id'], ['services_spdk_subsys.id'], name=op.f('fk_services_spdk_namespace_spdk_namespace_subsys_id_services_spdk_subsys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_namespace')),
    sa.UniqueConstraint('spdk_namespace_device_nguid', name=op.f('uq_services_spdk_namespace_spdk_namespace_device_nguid')),
    sa.UniqueConstraint('spdk_namespace_device_path', name=op.f('uq_services_spdk_namespace_spdk_namespace_device_path')),
    sa.UniqueConstraint('spdk_namespace_device_uuid', name=op.f('uq_services_spdk_namespace_spdk_namespace_device_uuid'))
    )
    with op.batch_alter_table('services_spdk_namespace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_spdk_namespace_spdk_namespace_subsys_id'), ['spdk_namespace_subsys_id'], unique=False)
        batch_op.create_index('services_spdk_namespace_spdk_namespace_subsys_id__spdk_namespace_nsid_uniq', ['spdk_namespace_subsys_id', 'spdk_namespace_nsid'], unique=True)

    op.create_table('services_spdk_port_subsys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spdk_port_subsys_port_id', sa.Integer(), nullable=False),
    sa.Column('spdk_port_subsys_subsys_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spdk_port_subsys_port_id'], ['services_spdk_port.id'], name=op.f('fk_services_spdk_port_subsys_spdk_port_subsys_port_id_services_spdk_port')),
    sa.ForeignKeyConstraint(['spdk_port_subsys_subsys_id'], ['services_spdk_subsys.id'], name=op.f('fk_services_spdk_port_subsys_spdk_port_subsys_subsys_id_services_spdk_subsys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_spdk_port_subsys')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('services_spdk_port_subsys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_spdk_port_subsys_spdk_port_subsys_port_id'), ['spdk_port_subsys_port_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_spdk_port_subsys_spdk_port_subsys_subsys_id'), ['spdk_port_subsys_subsys_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_spdk_port_subsys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_spdk_port_subsys_spdk_port_subsys_subsys_id'))
        batch_op.drop_index(batch_op.f('ix_services_spdk_port_subsys_spdk_port_subsys_port_id'))

    op.drop_table('services_spdk_port_subsys')
    with op.batch_alter_table('services_spdk_namespace', schema=None) as batch_op:
        batch_op.drop_index('services_spdk_namespace_spdk_namespace_subsys_id__spdk_namespace_nsid_uniq')
        batch_op.drop_index(batch_op.f('ix_services_spdk_namespace_spdk_namespace_subsys_id'))

    op.drop_table('services_spdk_namespace')
    with op.batch_alter_table('services_spdk_host_subsys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_spdk_host_subsys_spdk_host_subsys_subsys_id'))
        batch_op.drop_index(batch_op.f('ix_services_spdk_host_subsys_spdk_host_subsys_host_id'))

    op.drop_table('services_spdk_host_subsys')
    op.drop_table('services_spdk_subsys')
    op.drop_table('services_spdk_port')
    op.drop_table('services_spdk_host')
    op.drop_table('services_spdk_global')
    # ### end Alembic commands ###
